### PR TITLE
Static markup search and 404

### PR DESCRIPTION
**Pull request by saison**
Add search result page and 404 page

plz Review
@shunjikonishi

### CODE REVIEW

**Comment by shunjikonishi** [comment]
In #5, you changed the structure of files.
So probably this pull request can not merge directly.

Please rebase master to this branch and push again.

**Comment by saison** [comment]
This branch rebase master.

plz review
@shunjikonishi

**Comment by shunjikonishi** [comment]
## Move ejs files to child directory

I think *.ejs should be in ejs directory.

## Remove *.html

You can generate *.html by gulp, so you don't have to include them in repo.
Also it is better to output generated html files to html directory.

**Comment by shunjikonishi** [comment]
In #3, you unify *.scss to style.scss. But in this pull request, you split it.  
You should unify.

**Comment by saison** [comment]
plz review
@shunjikonishi

**Comment by shunjikonishi** [comment]
LGTM

**Pull request merged**
