### PR TITLE
SinglePage MarkUp & Design

### PR DESCRIPTION
**Pull request by saison**
plz Review
@shunjikonishi , @da0shi

### CODE REVIEW

**Comment by saison** [comment]
plz Re-review
@shunjikonishi , @da0shi

**Comment by takayukioda** [comment]
For both fixed and single page; I wonder why the .thumbnail and the .giveryMission don't have prefix 'singlePost__'? Since they seem to be same depth with such as .singlePost__body or .singlePost__info.

other than that, LGTM:+1:

**Comment by tak723sio** [comment]
add prefix 'singlePost__' & this branch rebase master

plz review
@da0shi , @shunjikonishi

**Comment by takayukioda** [comment]
lgtm

**Comment by saison** [comment]
add prefix & rebase master

plz review
@da0shi , @shunjikonishi

**Pull request merged**
